apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jxg3hhian-nodejs 
  janus-idp.io/tekton: jxg3hhian-nodejs
  backstage.io/kubernetes-id: jxg3hhian-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jxg3hhian-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml