apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jxg3hhian-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jxg3hhian-nodejs 
  name: jxg3hhian-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jxg3hhian-nodejs 
